
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "trust-io-team"
    assignees:
      - "trust-io-team"
    commit-message:
      prefix: "security"
      include: "scope"
