
name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'app/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd app
        npm ci --legacy-peer-deps
    
    - name: Run security audit
      run: |
        cd app
        npm audit --audit-level=high --omit=dev
    
    - name: Check for vulnerabilities
      run: |
        cd app
        npm audit --audit-level=critical --omit=dev
        
    - name: Build application
      run: |
        cd app
        npm run build
        
    - name: Test SWC dependencies
      run: |
        cd app
        node -e "require('@swc/core'); console.log('SWC OK')"
